name: kliniku
description: Project APB Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Buat only one time onboarding
  shared_preferences: ^2.0.13
  # Curved Navigation
  curved_navigation_bar: ^1.0.3
  # Maps
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.3
  cloud_firestore: ^3.1.12
  fluttertoast: ^8.0.9
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # Arimo
    - family: Arimo
      fonts:
        - asset: fonts/Arimo-Regular.ttf
        - asset: fonts/Arimo-Bold.ttf
          weight: 700
    # Montserrat
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    #  Nunito
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
        - weight: 700
    # Roboto
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
